[cursor]
blink_interval = 200
blink_timeout = 0
thickness = 0.4

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 18.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"

[keyboard]
bindings = [{ key = "V", mods = "Shift|Control", action = "Paste" },]

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/oksolar.toml",
  "~/.config/alacritty/emacs/alacritty-for-term-keys.toml",
]
