[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/kitty"
hook = "[ -n \"$KITTY_PID\" ] && kill -USR1 \"$KITTY_PID\""
supported-systems = ["base16"]
