#!/bin/sh

# X settings
xset s off
xset dpms 0 0 0
xsetroot -cursor_name left_ptr &

# startup apps
dunst &
nm-applet &
if [ $(uname -n) = "stinky" ]; then
    blueman-applet &
fi
wmname LG3D
#stalonetray &
keepassxc &
#megasync &
syncthing &
# TODO: cbatticon for BAT1 and BAT0
#multiload-ng-systray &
#dwmblocks &

if [ -d "/etc/X11/xinit/xinitrc.d" ]; then
    for f in /etc/X11/xinit/xinitrc.d/*.sh; do
        source "$f"
    done
fi

# startup script
startup
