# OKSolar - solarized adapted to OKLab perceptual colorspace
# https://meat.io/oksolar

# special
foreground                   #748587
background                   #002b36
selection_foreground         #002b36
selection_background         #748587

cursor                       #748587
cursor_text_color            #002b36

# black
color0   #093946
color8   #002b36

# red
color1   #d7474e
color9   #c16424

# green
color2   #798b04
color10  #536970

# yellow
color3   #a07b0d
color11  #657377

# blue
color4   #1d87ce
color12  #748587

# magenta
color5   #c74d90
color13  #7477c7

# cyan
color6   #13948b
color14  #93a1a1

# white
color7   #d4cfc1
color15  #e4e0d8