# vim:ft=kitty

## name:     base16 OKTwilight
## author:   chrispwd (https://github.com/chrispwd)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 OKTwilight
# Scheme author: chrispwd (https://github.com/chrispwd)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #282828
foreground #9e9e9e
selection_background #9e9e9e
selection_foreground #464b50

# Cursor colors
cursor #9e9e9e
cursor_text_color #282828

# URL underline color when hovering with mouse
url_color #838184

# Kitty window border colors
active_border_color #5f5a60
inactive_border_color #323537

# OS Window titlebar colors
wayland_titlebar_color #282828
macos_titlebar_color #282828

# Tab bar colors
active_tab_background #282828
active_tab_foreground #a7a7a7
inactive_tab_background #323537
inactive_tab_foreground #838184
tab_bar_background #323537

# The 16 terminal colors
# normal
color0 #282828
color1 #cf6a4c
color2 #98a672
color3 #aca14c
color4 #7587a6
color5 #9b859d
color6 #8ca1b7
color7 #9e9e9e

# bright
color8 #5f5a60
color9 #cf6a4c
color10 #98a672
color11 #aca14c
color12 #7587a6
color13 #9b859d
color14 #8ca1b7
color15 #dedede

# extended base16 colors
color16 #cda869
color17 #9b703f
color18 #323537
color19 #464b50
color20 #838184
color21 #c3c3c3