#!/bin/sh

startup

if [[ "$1" -eq 0 ]]; then
    echo "$1" >> /tmp/bspwm-log
    bspwm-assign-desktops &
else
    echo "$1" >> /tmp/bspwm-log
    bspwm-reload-desktops &
fi
# monitor
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# window
bspc config border_width                1
bspc config window_gap                  0
bspc config top_padding                 0
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio                 0.55
bspc config borderless_monocle          false
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child
bspc config center_pseudo_tiled         false

# pointer
bspc config pointer_follows_focus       true
bspc config focus_follows_pointer       true

# remove all rules before wm restart
bspc rule -r "*"

# rules
#bspc rule -a KeePassXC state=floating follow=on rectangle=800x600+0+0
bspc rule -a MEGAsync state=floating border=off rectangle=402x564+1500+30

# colors
## Solarized Dark
#bspc config normal_border_color     "#002b36"
#bspc config active_border_color     "#002b36"
#bspc config focused_border_color    "#eee8d5"
#bspc config presel_feedback_color   "#eee8d5"
#bspc config focused_border_color    "#2aa198"
#bspc config presel_feedback_color   "#2aa198"
## One Dark
#bspc config normal_border_color     "#1e2127"
#bspc config active_border_color     "#1e2127"
#bspc config focused_border_color    "#abb2bf"
#bspc config presel_feedback_color   "#abb2bf"
## palenight
#bspc config normal_border_color     "#434758"
#bspc config active_border_color     "#434758"
#bspc config focused_border_color    "#d0d0d0"
#bspc config presel_feedback_color   "#d0d0d0"
## Nord
#bspc config normal_border_color     "#2e3440"
#bspc config active_border_color     "#2e3440"
#bspc config focused_border_color    "#d8dee9"
#bspc config presel_feedback_color   "#d8dee9"
## Tomorrow Dark
#bspc config normal_border_color      "#1d1f21"
#bspc config active_border_color      "#1d1f21"
#bspc config focused_border_color     "#c5c8c6"
#bspc config presel_feedback_color    "#c5c8c6"
## Ayu Dark
bspc config normal_border_color      "#444b55"
bspc config active_border_color      "#636a72"
bspc config focused_border_color     "#39bae6"
bspc config presel_feedback_color    "#ffb454"
## Isotope Dark
#bspc config normal_border_color     "#000000"
#bspc config active_border_color     "#000000"
#bspc config focused_border_color    "#d0d0d0"
#bspc config presel_feedback_color   "#d0d0d0"
## Twilight
#bspc config normal_border_color     "#1e1e1e"
#bspc config active_border_color     "#1e1e1e"
#bspc config focused_border_color    "#a7a7a7"
#bspc config presel_feedback_color   "#a7a7a7"

#bspwm-assign-desktops && sleep 1
$XDG_CONFIG_HOME/polybar/launch.sh &
