## name: cemant
## author: agaric <agaric@pm.me>
## license: MIT
## blurb: 18-color palette for use with terminals, text editors, and minimalistic desktop environments.

foreground               #36383f
background               #b9bdc5
# selection_foreground     #
selection_background     #92959d

cursor                   #16161d
cursor_text_color        #36383f

url_color                #3c56aa

# active_tab_foreground    #989898
# active_tab_background    #000000
# inactive_tab_foreground  #424242
# inactive_tab_background  #191919

# black
color0      #16161d
color8      #575a61

# red
color1      #a32c2d
color9      #cf554d

# green
color2      #4b7d08
color10     #72a336

# yellow
color3      #916814
color11     #ba8d3b

# blue
color4      #3c56aa
color12     #667ad3

# magenta
color5      #91328c
color13     #ba59b3

# cyan
color6      #237e6f
color14     #4ea494

# white
color7      #92959d
color15     #d2d6de
