# OKSolar - solarized adapted to OKLab perceptual colorspace
# https://meat.io/oksolar

# special
foreground                   #839396
background                   #002d38
selection_foreground         #002d38
selection_background         #839396

cursor                       #839396
cursor_text_color            #002d38

# black
color0   #093946
color8   #002d38

# red
color1   #f23749
color9   #d56500

# green
color2   #819500
color10  #5b7279

# yellow
color3   #ac8300
color11  #657377

# blue
color4   #2b90d8
color12  #839396

# magenta
color5   #dd459d
color13  #7d80d1

# cyan
color6   #259d94
color14  #8faaab

# white
color7   #f1e9d2
color15  #fbf7ef