# vim:ft=kitty

## name:     base16 OKTwilight
## author:   chrispwd (https://github.com/chrispwd)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    

# Scheme name: base16 OKTwilight
# Scheme author: chrispwd (https://github.com/chrispwd)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1e1e1e
foreground #878787
selection_background #878787
selection_foreground #5f5a60

# Cursor colors
cursor #878787
cursor_text_color #282828

# URL underline color when hovering with mouse
url_color #838184

# Kitty window border colors
active_border_color #5f5a60
inactive_border_color #323537

# OS Window titlebar colors
wayland_titlebar_color #282828
macos_titlebar_color #282828

# Tab bar colors
active_tab_background #282828
active_tab_foreground #a7a7a7
inactive_tab_background #323537
inactive_tab_foreground #838184
tab_bar_background #323537

# The 16 terminal colors
# normal
color0 #282828
color1 #cf6a4c
color2 #8b9965
color3 #9d923c
color4 #7587a6
color5 #9b859d
color6 #73969d
color7 #b2b2b2

# bright
color8 #323537
color9 #b2883a
color10 #5f5a60
color11 #7b797c
color12 #878787
color13 #b2b2b2
color14 #9b703f
color15 #dedede

# extended base16 colors
color16 #cda869
color17 #9b703f
color18 #323537
color19 #464b50
color20 #838184
color21 #c3c3c3