[schemes.doom-one.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[schemes.doom-one.cursor]
cursor = "#528bff"
text = "CellBackground"

[schemes.doom-one.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#202328"
yellow = "#da8548"

[schemes.doom-one.primary]
background = "#282c34"
foreground = "#bbc2cf"

[schemes.doom-one.selection]
background = "#3e4451"
text = "CellForeground"

[schemes.dracula.bright]
black = "#4d4d4d"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[schemes.dracula.cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.dracula.dim]
black = "#14151b"
blue = "#4d5b86"
cyan = "#59dffc"
green = "#1ef956"
magenta = "#ff46b0"
red = "#ff2222"
white = "#e6e6d1"
yellow = "#ebf85b"

[schemes.dracula.line_indicator]
background = "None"
foreground = "None"

[schemes.dracula.normal]
black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[schemes.dracula.primary]
background = "#282a36"
foreground = "#f8f8f2"

[schemes.dracula.search.bar]
background = "#282a36"
foreground = "#f8f8f2"

[schemes.dracula.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[schemes.dracula.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[schemes.dracula.selection]
background = "#44475a"
text = "CellForeground"

[schemes.dracula.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.gruvbox-dark.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[schemes.gruvbox-dark.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[schemes.gruvbox-dark.primary]
background = "#000000"
foreground = "#ebdbb2"

[schemes.modus-vivendi.bright]
black = "0x595959"
blue = "0x4fafff"
cyan = "0x3fdfd0"
green = "0x4fe42f"
magenta = "0xff62d4"
red = "0xfe6060"
white = "0xe0e6f0"
yellow = "0xf0dd60"

[schemes.modus-vivendi.cursor]
cursor = "#ffffff"
text = "#000000"

[schemes.modus-vivendi.normal]
black = "0x100f10"
blue = "0x2fafff"
cyan = "0x00d3d0"
green = "0x44bc44"
magenta = "0xfeacd0"
red = "0xff8059"
white = "0xa8a8a8"
yellow = "0xd0bc00"

[schemes.modus-vivendi.primary]
background = "#000000"
foreground = "#ffffff"

[schemes.monokai-pro.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.monokai-pro.normal]
black = "#403E41"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.monokai-pro.primary]
background = "#2D2A2E"
foreground = "#FCFCFA"

[schemes.nord.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[schemes.nord.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[schemes.nord.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[schemes.oceanic-next.bright]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[schemes.oceanic-next.cursor]
cursor = "#ffffff"
text = "#1b2b34"

[schemes.oceanic-next.normal]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[schemes.oceanic-next.primary]
background = "#1b2b34"
foreground = "#d8dee9"

[schemes.palenight.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#e1acff"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[schemes.palenight.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#d0d0d0"
yellow = "#ffcb6b"

[schemes.palenight.primary]
background = "#292d3e"
foreground = "#ffffff"

[schemes.solarized-dark.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized-dark.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.solarized-dark.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized-dark.primary]
background = "#002b36"
foreground = "#839496"

[schemes.solarized-dark-black-bg.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized-dark-black-bg.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.solarized-dark-black-bg.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized-dark-black-bg.primary]
background = "#000000"
foreground = "#839496"

[schemes.solarized-light.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized-light.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[schemes.solarized-light.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized-light.primary]
background = "#fdf6e3"
foreground = "#657b83"

[schemes.badger.primary]
background = "#171717"
foreground = "#f6f3e8"

[schemes.badger.normal]
black = "#1d1d1d"
red = "#E2434C"
green = "#86B187"
yellow = "#E0D063"
blue = "#2257A0"
magenta = "#BF93C3"
cyan = "#00cdcd"
white = "#656868"

[schemes.badger.bright]
black = "#433f4f"
red = "#EA9847" 
green = "#65A399" 
yellow = "#E0D063" 
blue = "#8AC6F2" 
magenta = "#E18Cbb" 
cyan = "5699AF"
white = "#dfdfdf"

[schemes.badger.cursor]
cursor = "#8ac6f2"
text = "#171717"
